### ISSUE TITLE
Promise syntax?

### ISSUE THREAD

**Issue by TimothyMischief** [mattias800/react-native-relay-facebook-neo4j-starter-kit#1]
Hey man, thanks so much for this repo, it's helped immensely as I'm trying to learn React and Relay.

I'm new to actively using github so just let me know if questions should be posted elsewhere.

I'm trying to understand your database interface and getting a little caught at the syntax around the promises in the Services. [https://github.com/mattias800/react-native-relay-facebook-neo4j-starter-kit/blob/master/graphql/src/persistence/service/UserService.js#L19](url) in particular the `Promise<Array<User>>` chunk. I've been digging through the ES6 and JSX syntax and I can't find anything that looks remotely like that. Is it taking advantage of JSX syntactic sugar in a weird way?

I'm assuming in some way it's building some kind of structural expectation of what the promise will return with the class you defined in the UserEntity, but I'm not clear on exactly how it's doing that or if it is actually doing that. I tried to use the syntax in a simple setup in isolation and transpile it to try to break it down but only wound up with errors.

Any help is massively appreciated!

Thanks again.

**Comment by mattias800** [comment]
Hello!

That is the return type of the function. It uses Flowtype (1) for type checking.
<X> syntax is generics.
So the function will return a Promise that will resolve with an array of User objects.

Hope that helps :)

(1) https://flowtype.org/

**Comment by TimothyMischief** [comment]
That helps heaps, thanks!
